kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
  - name: test-echo
    image: alpine
    commands:
      - echo "Hi"
    when:
      branch:
        - sam-test-branch-drone
      event:
        - push