---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: testsuite
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - docker run --rm -v $(pwd):/data -w /data hashicorp/terraform fmt --diff --check
  when:
    event:
    - push

- name: run-testrunner-tests
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/tf-testrunner:32
  commands:
  - python -m unittest tests/*_test.py
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  when:
    event:
    - push

services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
